In [1]:
#pip install ISLP

  Obtaining dependency information for ISLP from https://files.pythonhosted.org/packages/f3/fa/857dad1d6bc7dffe1020944ab6ef4c038bc6f19bc35bf06e1fb92c6e1912/ISLP-0.4.0-py3-none-any.whl.metadata
  Obtaining dependency information for lxml from https://files.pythonhosted.org/packages/05/9e/87492d03ff604fbf656ed2bf3e2e8d28f5d58ea1f00ff27ac27b06509079/lxml-5.3.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata
  Obtaining dependency information for statsmodels>=0.13 from https://files.pythonhosted.org/packages/78/44/d72c634211797ed07dd8c63ced4ae11debd7a40b24ee80e79346a526194f/statsmodels-0.14.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for lifelines from https://files.pythonhosted.org/packages/14/f7/379e185a75ac8166ac70756d0ba68d9a2b02b555c7fde4983246752396bd/lifelines-0.30.0-py3-none-any.whl.metadata
  Obtaining dependency information for pygam from https://files.pythonhosted.org/packages/ea/a7/d7037173f7c39fd114ca7bc9757149bdfbe29

In [2]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [3]:
print?

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [4]:
3+5

8

In [5]:
"hello" + " " + "world"

'hello world'

In [7]:
x = [3, 4, 5]
x

[3, 4, 5]

In [8]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

In [9]:
# Reference: https://numpy.org/doc/stable/user/quickstart.html
import numpy as np

In [10]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [11]:
x + y

array([ 7, 13, 12])

In [12]:
# two dimensional array
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [13]:
x.ndim # 2 dimensional array

2

In [15]:
x.dtype # x is comprised of 64-bit integers

dtype('int64')

In [17]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [18]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [19]:
np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [20]:
x.shape # number of rows and columns

(2, 2)

In [29]:
x = np.array([1, 2, 3, 4])
x.sum()

10

In [30]:
np.sum(x)

10

In [31]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [32]:
# 0 based indexing in Python vs R which is 1
x_reshape[0, 0]

1

In [33]:
x_reshape[1, 2]

6

In [34]:
print('x before we modify x_reshape:\n', x)
print('x_reshape before we modify x_reshape:\n', x_reshape)
x_reshape[0, 0] = 5
print('x_reshape after we modify its top left element:\n',
      x_reshape)
print('x after we modify top left element of x_reshape:\n', x)

x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


In [35]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment